### ISSUE TITLE
Plot single record containing multiple parameters

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#157]
**Background**
Since ert3 allows to define parameters as a group, eg. 
```yaml
-
  name: coefficients
  type: stochastic
  distribution:
    type: gaussian
    input:
      mean: 0
      std: 1
  variables: ["a", "b", "c"]
```
they are stored as `record_class=ds.RecordClass.parameter` and  `record_type=ds.RecordType.f64_matrix,`, where record column labels represent variable names `["a", "b", "c"]` and index column defines different realizations. Currently, `webviz-ert` doesn't visualize such type of parameters.

**Approach**
Create a dedicated `PlotModel` class which would be able to handle such parameters. An initial approach could be just to create (automatically) multiple histogram views (separate graphs), ie. for `a`,`b` and `c` for a parameter that is called `coefficients`.

Link to the accompanied discussion https://github.com/equinor/ert/issues/1720 that spawned this issue.
